name: Article Draft PR

on:
    push:
        branches:
            - blog/*
        paths:
            - '**/content/blog/**.md'
    workflow_dispatch:

jobs:
    create_pr:
        name: Create Draft PR
        runs-on: ubuntu-latest

        steps:
            - name: Create Github Apps Token
              uses: actions/create-github-app-token@v1
              id: gh_token
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Check already existing PR
              id: check_pr
              run: |
                    gh pr list --state open --base main --head $GITHUB_REF
              env:
                  GH_TOKEN: ${{ steps.gh_token.outputs.token }}
                  GITHUB_REF: ${{ github.ref }}
            
            - name: Create PR
              if: steps.check_pr.outputs.stdout == ''
              run: |
                    gh pr create --base main --head $GITHUB_REF --title "Draft PR for $GITHUB_REF" --body "This is a draft PR for $GITHUB_REF"
              env:
                  GH_TOKEN: ${{ steps.gh_token.outputs.token }}
                  GITHUB_REF: ${{ github.ref }}